#define conc(b7,b6,b5,b4,b3,b2,b1,b0) conc_Help(b7,b6,b5,b4,b3,b2,b1,b0)
#define conc_Help(b7,b6,b5,b4,b3,b2,b1,b0) 0b##b7##b6##b5##b4##b3##b2##b1##b0
#define PORTA_DIR conc(PORTA_PIN7_DIR,PORTA_PIN6_DIR,PORTA_PIN5_DIR,PORTA_PIN4_DIR,PORTA_PIN3_DIR,PORTA_PIN2_DIR,PORTA_PIN1_DIR ,PORTA_PIN0_DIR)
#define PORTB_DIR conc(PORTB_PIN7_DIR,PORTB_PIN6_DIR,PORTB_PIN5_DIR,PORTB_PIN4_DIR,PORTB_PIN3_DIR,PORTB_PIN2_DIR,PORTB_PIN1_DIR ,PORTB_PIN0_DIR)
#define PORTC_DIR conc(PORTC_PIN7_DIR,PORTC_PIN6_DIR,PORTC_PIN5_DIR,PORTC_PIN4_DIR,PORTC_PIN3_DIR,PORTC_PIN2_DIR,PORTC_PIN1_DIR ,PORTC_PIN0_DIR)
#define PORTD_DIR conc(PORTD_PIN7_DIR,PORTD_PIN6_DIR,PORTD_PIN5_DIR,PORTD_PIN4_DIR,PORTD_PIN3_DIR,PORTD_PIN2_DIR,PORTD_PIN1_DIR ,PORTD_PIN0_DIR)
                      
                      
                      
#define PORTA_INTIALVALUE conc(PORTA_PIN7_INTIALVALUE,PORTA_PIN6_INTIALVALUE,PORTA_PIN5_INTIALVALUE,PORTA_PIN4_INTIALVALUE,PORTA_PIN3_INTIALVALUE,PORTA_PIN2_INTIALVALUE,PORTA_PIN1_INTIALVALUE ,PORTA_PIN0_INTIALVALUE)
#define PORTB_INTIALVALUE conc(PORTB_PIN7_INTIALVALUE,PORTB_PIN6_INTIALVALUE,PORTB_PIN5_INTIALVALUE,PORTB_PIN4_INTIALVALUE,PORTB_PIN3_INTIALVALUE,PORTB_PIN2_INTIALVALUE,PORTB_PIN1_INTIALVALUE ,PORTB_PIN0_INTIALVALUE)
#define PORTC_INTIALVALUE conc(PORTC_PIN7_INTIALVALUE,PORTC_PIN6_INTIALVALUE,PORTC_PIN5_INTIALVALUE,PORTC_PIN4_INTIALVALUE,PORTC_PIN3_INTIALVALUE,PORTC_PIN2_INTIALVALUE,PORTC_PIN1_INTIALVALUE ,PORTC_PIN0_INTIALVALUE)
#define PORTD_INTIALVALUE conc(PORTD_PIN7_INTIALVALUE,PORTD_PIN6_INTIALVALUE,PORTD_PIN5_INTIALVALUE,PORTD_PIN4_INTIALVALUE,PORTD_PIN3_INTIALVALUE,PORTD_PIN2_INTIALVALUE,PORTD_PIN1_INTIALVALUE ,PORTD_PIN0_INTIALVALUE)
                      