//input 0 output 1
#define PORTA_PIN0_DIR 1
#define PORTA_PIN1_DIR 1
#define PORTA_PIN2_DIR 1
#define PORTA_PIN3_DIR 1
#define PORTA_PIN4_DIR 1
#define PORTA_PIN5_DIR 1
#define PORTA_PIN6_DIR 1
#define PORTA_PIN7_DIR 1

#define PORTB_PIN0_DIR 1
#define PORTB_PIN1_DIR 1
#define PORTB_PIN2_DIR 0
#define PORTB_PIN3_DIR 0
#define PORTB_PIN4_DIR 0
#define PORTB_PIN5_DIR 0
#define PORTB_PIN6_DIR 0
#define PORTB_PIN7_DIR 0

#define PORTC_PIN0_DIR 0
#define PORTC_PIN1_DIR 0
#define PORTC_PIN2_DIR 0
#define PORTC_PIN3_DIR 0
#define PORTC_PIN4_DIR 0
#define PORTC_PIN5_DIR 0
#define PORTC_PIN6_DIR 0
#define PORTC_PIN7_DIR 0

#define PORTD_PIN0_DIR 0
#define PORTD_PIN1_DIR 0
#define PORTD_PIN2_DIR 0
#define PORTD_PIN3_DIR 0
#define PORTD_PIN4_DIR 0
#define PORTD_PIN5_DIR 0
#define PORTD_PIN6_DIR 0
#define PORTD_PIN7_DIR 0
/*set intial value of  pin*/
#define PORTA_PIN0_INTIALVALUE 0
#define PORTA_PIN1_INTIALVALUE 0
#define PORTA_PIN2_INTIALVALUE 0
#define PORTA_PIN3_INTIALVALUE 0
#define PORTA_PIN4_INTIALVALUE 0
#define PORTA_PIN5_INTIALVALUE 0
#define PORTA_PIN6_INTIALVALUE 0
#define PORTA_PIN7_INTIALVALUE 0
									
#define PORTB_PIN0_INTIALVALUE 0
#define PORTB_PIN1_INTIALVALUE 0
#define PORTB_PIN2_INTIALVALUE 0
#define PORTB_PIN3_INTIALVALUE 0
#define PORTB_PIN4_INTIALVALUE 0
#define PORTB_PIN5_INTIALVALUE 0
#define PORTB_PIN6_INTIALVALUE 0
#define PORTB_PIN7_INTIALVALUE 0
									
#define PORTC_PIN0_INTIALVALUE 1
#define PORTC_PIN1_INTIALVALUE 1
#define PORTC_PIN2_INTIALVALUE 1
#define PORTC_PIN3_INTIALVALUE 1
#define PORTC_PIN4_INTIALVALUE 1
#define PORTC_PIN5_INTIALVALUE 1
#define PORTC_PIN6_INTIALVALUE 1
#define PORTC_PIN7_INTIALVALUE 1
									
#define PORTD_PIN0_INTIALVALUE 1
#define PORTD_PIN1_INTIALVALUE 1
#define PORTD_PIN2_INTIALVALUE 1
#define PORTD_PIN3_INTIALVALUE 1
#define PORTD_PIN4_INTIALVALUE 1
#define PORTD_PIN5_INTIALVALUE 1
#define PORTD_PIN6_INTIALVALUE 1
#define PORTD_PIN7_INTIALVALUE 1
